### ISSUE TITLE
torro_loaded hook have to be hooked before executing

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#179]
To get sure that the user can access the torro_loaded action hook, the hook have to be moved to another part of code which is already hooked or the includes function have to be hooked, which can be a bit mor complicated. If we are not doing that, the user has no chance to hook into torro_loaded, if his plugin is loaded after Torro Forms. 

The hook at the moment:
https://github.com/awsmug/torro-forms/blob/master/torro-forms.php#L196

**Comment by felixarntz** [comment]
I don't think this is a problem. All plugins have been loaded at the `plugins_loaded` hook, so one can always access the hook. What we might do is add a function `torro_loaded( $callback )` that can be used instead of the hook. This can behave like this: If the hook has executed already, run the callback immediately, otherwise attach it to the hook.

**Comment by felixarntz** [comment]
I fixed this in 277d0e76aaa8454ff0d09daab786801a52be2e57. All extensions should use `torro_loaded( $callback )` and pass a callback into the function. The `torro_loaded` hook no longer exists and was replaced by a `_torro_loaded` hook which should not be used publicly (let's exclude it from the list of hooks in the documentation as well).
