### ISSUE TITLE
torro() function which does not make sense

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#186]
I will collect all sub functions of the torro() functions which does not make sense.

- torro()->forms()->register();
- torro()->containers()->register();

Please do not close the ticket until I have collected them all.

**Comment by felixarntz** [comment]
torro()->forms()->copy() is valid I think, as you can use it to duplicate a form.

**Comment by felixarntz** [comment]
The problem with the registration-related methods was that actually no instance manager should have them. That's why in 3b5a0d4b1f9aed9df72f1895c90ec05ff8de9433 the instance manager class is no longer a child of the regular manager class.

The only instance where we needed the registration methods were elements. However this was actually inaccurate since we're not registering elements, but element types. Therefore I introduced a new manager class `Torro_Element_Types_Manager` which now manages all element types. The `Torro_Elements_Manager` class is now solely responsible for actual elements (in the database).
