### ISSUE TITLE
Datepicker overflow

### ISSUE THREAD

**Issue by krafit** [awsmug/torro-forms#208]
Well the calendar overflows its parent element 😢

Bonus Issue: .ui-datepicker-trigger could use `.dashicons-calendar-alt` 😬

![bildschirmfoto 2016-05-30 um 15 24 09](https://cloud.githubusercontent.com/assets/1038789/15650713/ea517980-267a-11e6-95c9-30a09fd07913.png)

**Comment by mahype** [comment]
I have checked it in different Browsers on Mac and Win. I can't reproduce the error. Can you tell me which system and which Browser you are using.

It also can be that the problem is occurred by another plugin which is loading it's own CSS at all wp-admin pages. If you can confirm that, I need the plugin name and I will remove the plugin CSS in our compat.php.

**Comment by krafit** [comment]
Oh yes, other plugins....

It's ACF (pro)

**Comment by mahype** [comment]
I don't have ACF pro and with the base version I also don't have the problems. Can you tell me how is the CSS hooked that I can unhook it or do a pull request by using the compat.php?

**Comment by mahype** [comment]
If you doing a pull request, please use the develop branch ;)

**Comment by mahype** [comment]
Hi Simon,

can you give me some more information about the hooking of the CSS that I can dehook the scripts. That would be reeeally great! :)

Greetings,

Sven

**Comment by mahype** [comment]
I have removed the milestone because of no further information. We well add it to a new milestone if we have more information.
