### ISSUE TITLE
Changing multiple answer appearance in Email Notifications

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#248]
Changing from UL list to comma separated values and adding a filter that everybody can change values for their needs.

**Comment by hutsori** [comment]
Great! This works fine.  :)

One thing I would comment is when you click "show details" in the results entries, you'll have duplicate questions if you have 2 or more answers. 

Say you have a question: 

> What are your favorite food? 
> 1. Water
> 2. Ice cream
> 3. Steak
> 4. Coke

And you choose 1 and 4 as your answer, then you would see

> What are your favorite food?   Water
> What are your favorite food?   Coke

when you click "Show Details" instead of 

> What are your favorite food? Water, Coke

What do you think?
