### ISSUE TITLE
Sidebar should be fixed

### ISSUE THREAD

**Issue by zottto** [awsmug/torro-forms#278]
When editing a long form, the sidebar is not in fixed position so one always has to scroll to top to reach the possible new elements of the form.
It would be better, if the sidebar would be "position:fixed", so that the widget for the new elements is always visible.

Thanks,
Marc

**Comment by felixarntz** [comment]
I don't think fixing the sidebar is a good idea since that would be WordPress Core business. Only fixing our own metabox wouldn't make too much sense as long as Core doesn't fix all their sidebar metaboxes.

We might think about alternative placements for the metabox altogether. Feel free to share your ideas :)
