### ISSUE TITLE
Image poll question and Mycred support

### ISSUE THREAD

**Issue by alexlii1971** [awsmug/torro-forms#326]
Hello,

Really great work, thanks.

I am not techincal, and actually I work as Marketing expert, so I tested a lot survey, poll, even LMS plugins.

It would be much better if torro-forms can support mycred. I am using WP POLL now, it is standard wordpress post and support Mycred to award site visitors points, and encourage them to involve in Poll.  some plugin may does not support mycred, but they may develope a little addon or extension to support that, here is  the mycred addon for total poll for your reference: https://mycred.me/store/mycred-for-totalpoll/. it is possible to support mycred for Torro-forms?

By the way, it does not support picture choice in a poll, will it support that future?

Thanks again, and have a nice day.

Alex

**Comment by mahype** [comment]
Hi Alex,

I have added your Idea of mycred support to our Idea issue list. But I can’t promise that we will support this in future.

The possibility to add images to Multiple and One Answer elements will come definetly. Several people asked for that functionality. We have already a ticket for that:

https://github.com/awsmug/torro-forms/issues/215

Greetings,

Sven

**Comment by alexlii1971** [comment]
Hi Sven,

Thanks for replay, it would great if it support adding a conditional logical in one choice and multiple choice elements too.

As to mycred, I understand, and thanks again.

Alex

**Comment by mahype** [comment]
HI Alex,

I have checked the MyCRED support. I see no problem if you put the shortcode into the section "Actions > Redirections > Text Message". There is an Editor and the shortcodes in it will be executed. You can do it like this:

`[mycred_give amount="10" log="He answered the Form" ref="bonus_points"]`

Please don't use the content element for it, because the content element will be executed before the user submits the whole data. That does not make sense.

For the conditional logic we already have an Issue. This will definetly implemented in the base version of Torro Forms.

https://github.com/awsmug/torro-forms/issues/244

Greetings,

Sven
