### ISSUE TITLE
Access Controls > Author Identification labeling

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#371]
![bildschirmfoto 2017-12-10 um 12 05 18](https://user-images.githubusercontent.com/663697/33804321-b1b923bc-dda2-11e7-8f45-ccc6fbaa50af.png)

Like in the other parts of the formbuilder, the form fields shold have a label on the left side and a description under the form field. As you can see in the screenshot, the bottom part in the "Actions" part has a left label. That case should be everywhere.

**Comment by felixarntz** [comment]
For accessibility reasons, single checkboxes should only have a label beside them, like there is for the above, so there must not be an additional label.

I agree it looks weird though when there are a bunch of checkboxes because then the whole left side stays blank. I already included a fix for tabs that only have such fields, however the problem is that the "Author Identification" also contains a conditional text field (which shows when checking the last box), so that logic cannot be applied there.

**Comment by felixarntz** [comment]
Done via b8a7c51797329868b941bc4f103c4607e4267ead, ff5a6fc9dcb5956246e18cd30f90bca57df54099 and 505a4787afe0afc6018d17d9382b354302fdf8de
