### ISSUE TITLE
Video playing doesn't work

### ISSUE THREAD

**Issue by tolgakutlu** [awsmug/torro-forms#427]
I have a problem with the plugin. My website: https://www.dutchyipsstudy.nl/start-dys/. I add a content element. Inside the content element I upload a video as media type or I add a html code to a video It works I see the video on the backand I can play it but on the frontand of the website the video doesn't play. What I add as code is
Backand
![afbeelding](https://user-images.githubusercontent.com/39030327/39865851-8cb0be04-544e-11e8-953f-851094d25229.png)
Backand
![afbeelding](https://user-images.githubusercontent.com/39030327/39865875-ab1a1372-544e-11e8-9be5-e2035dbcb42d.png)
Frontand
![afbeelding](https://user-images.githubusercontent.com/39030327/39865893-b969d2a0-544e-11e8-8ef1-cb6bb9bd5aa7.png)

I tried different webbrowsers I thought maybe the videoplayer of wordpress is the problem I add a another videoplayer plugin it didn't work. My torro plugin version 1.0.0-beta.10 and wordpress version 4.9.5

**Comment by tolgakutlu** [comment]
Will this problem be solved in Version 1.0.0-beta.12?

**Comment by felixarntz** [comment]
@tolgakutlu This problem appears not because of the plugin, but because of WordPress itself. When filtering content with `wp_kses_post()`, the `source` HTML tag is stripped out because it's not allowed. Strangely this doesn't happen on regular post content because it is handled differently, but for plugins using `wp_kses_post()` is recommended here (if you try it with the Custom HTML widget for example, it won't work either).

Summarizing, this is not a problem with the plugin itself, so it doesn't make sense to fix it here as it is not a common issue either. Let me help you with a code snippet instead. You can put the following into a custom plugin or your child theme's functions.php:
```php
function myplugin_allow_kses_video_markup( $allowedtags, $context ) {
	if ( 'post' === $context ) {
		if ( ! isset( $allowedtags['source'] ) ) {
			$allowedtags['source'] = array();
		}

		$allowedtags['source']['src']  = true;
		$allowedtags['source']['type'] = true;
	}

	return $allowedtags;
}
add_filter( 'wp_kses_allowed_html', 'myplugin_allow_kses_video_markup', 10, 2 );
```

With this in place, your video will appear.

**Comment by alexlii1971** [comment]
The same issue for me, and I tried your code sinppet, it works.
Alex
